import Image from "next/image";
import Link from "next/link";
import styles from "./page.module.css";
import { Main, About, Contact, Products } from "@/components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <Main />
      <About />
      <section className={styles.products}>
        <div className={styles.products__container}>
          <h2 className={styles.products__h2}>Nuestros Productos Destacados</h2>
          <Products />
        </div>
      </section>
      <Contact />
    </>
  );
}
