export const revalidate = 604800;


import styles from "./page.module.css";
import { getProductsPage } from "@/server/modules/product/actions/productActions";
import { Main, About, Products } from "@/components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Home() {

  const pageable = {size : 3, page : 0};
  const products = await getProductsPage(pageable);

  return (
    <>
      <Main />
      <About />
      <section className={styles.products}>
        <div className={styles.products__container}>
          <h2 className={styles.products__h2}>Nuestros Productos Destacados</h2>
          <Products products={products}/>
        </div>
      </section>
    </>
  );
}
